baseURL = 'https://viariogrande.org'
locale = 'en-us'
title = 'The Rio Grande Plan'
copyright = "Via Rio Grande"

defaultContentLanguage = "en"
# sectionPagesMenu = "main"

# [markup]
#   [markup.goldmark]
#     [markup.goldmark.renderer]
#       unsafe = true

[services.googleAnalytics]
id = ''

[cascade]
featured_image = '/images/ground-render.webp'
images = ['/images/ground-render.webp']

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/gohugo-ananke/ananke/v2'