text_color = "gray"
post_content_classes = "avenir"
site_logo = "images/logo.webp"
favicon = "images/favicon.png" # TODO: svg
description = "Utah’s next big move"

[ananke]
show_recent_posts = false
custom_css = ["site.css"]

[ananke.social.linkedin]
username = "via-rio-grande"

[ananke.social.youtube]
username = "CSLenhart"

[ananke.social.facebook]
username = '61566364769715'

[ananke.social.instagram]
username = 'riograndeplan'

[ananke.social.follow]
networks = ["instagram", "youtube", "facebook", "linkedin"]